### ISSUE TITLE
Naming boolean variables and functions returning boolean

### ISSUE THREAD

**Issue by kownacki** [9e15/guidelines#10]
Proposal.

Generally:
1. Name booleans like: `valid`, `playerReady`.
2. Name functions which return boolean values like `isValid`, `isPlayerReady`.

Example:
```js
const fooValid = isFooValid(foo);
```
Rationale:
1. Avoid confusion when naming this kind of variables. (should I use "is" or not?)
2. Consistent code.
3. Knowing whether a variable is a function or boolean by its name, and so for example avoiding using function like a boolean.

Note:
It also applies to properies and methods. 
Getters as they are used like normal properties should also be named like properties (without "is").

**Comment by merlinnot** [comment]
LGTM

**Comment by marcinkubicki** [comment]
Naming of properties and variables with 'is' IMO is good for reading code in conditional statement.
if(isReady) -> we expect more true to pass 
if(!isReady) -> we expect more false to pass
if(ready) -> we expected both to pass

True - "There are hundreds of opinions and often not one right solution."

I think consistency and everyone on a given team using the same standards/styles is the important thing to bear in mind.

I agree with proposal also.

**Comment by kownacki** [comment]
@marcinkubicki Yeah it is indeed more informative to use prefix "is" with booleans and it's certainly not wrong. But it makes them a little longer and I'd never be sure whether it's boolean or function. So I think it's not worth to attach "is" to booleans. It makes more sense for functions as it's nice to use verbs in function names to indicate action (`calculateSth`, `runThat`, `isStuffReady`).

All this is not really that crucial. So let's just agree on one way and stop worrying :)

**Comment by marcinkubicki** [comment]
Ok could be.
JS is so crazy an looks more or less like never ending callback hell and so on ;)

**Comment by kownacki** [comment]
Resolved by https://github.com/9e15/guidelines/pull/17
