### ISSUE TITLE
Favicons & manifests

### ISSUE THREAD

**Issue by merlinnot** [9e15/guidelines#12]
Require all checks to pass on all of the projects: http://realfavicongenerator.net/

**Comment by kownacki** [comment]
Driverpal and Uniheap pass this check right now. Should it be mentioned in the guidelines that PWA projects should pass this?

**Comment by merlinnot** [comment]
y

**Comment by merlinnot** [comment]
This repository seems to be unmaintained, I'll close the issue so it's no longer on my list.
