### ISSUE TITLE
JSDoc for Promises

### ISSUE THREAD

**Issue by kownacki** [9e15/guidelines#4]
JSDoc for Promises are not defined. Although people use various custom notations. 
Guys from Firebase use such notation: `Promise<type>`.
We need to decide how we are going to do this.

**Comment by merlinnot** [comment]
Let's follow FB until some standard lands.

**Comment by kownacki** [comment]
I still don't feel so JSDoc-savvy. I'll add this rule as soon as I feel I know what I'm doing.

**Comment by kownacki** [comment]
We are moving to TypeScript so JSDoc is now redundant.
