### ISSUE TITLE
Order of requires.

### ISSUE THREAD

**Issue by kownacki** [9e15/guidelines#5]

**Comment by merlinnot** [comment]
Same as in vscode.

**Comment by kownacki** [comment]
Be mindful that not everybody uses vscode and we definitely shouln't be dependent on one single IDE's plugin but rather refer to some kind of external standard.

---

I have a few ideas:

1. In javascript strings are compared based on standard lexicographical ordering, using Unicode values. Which is intuitive and reduces the wtf factor. We could follow that order also in our dependencies. Although it's a bit strange that `_` is between letters.
`ABC < _ < abc`. 

2. Same as in 1. but with exception for `_` to be always first.
`_ < ABC  < abc`.

What's the order in vscode?

**Comment by merlinnot** [comment]
Actually _ < [aA-zZ]

**Comment by kownacki** [comment]
So: _, a, A, b, B, c, C... ? Or maybe case is irrelevant?

**Comment by merlinnot** [comment]
Hmm, I need to check ;)

**Comment by mchyb** [comment]
VSCode doesn't take letter ase into consideration. I'd stick with `_, a, A, b, B, c, C, [...]`.

**Comment by kownacki** [comment]
Isn't `_, a, b, c, ...., z, A, B, C, ..., Z` more sane?

**Comment by merlinnot** [comment]
@mchyb then we should do the same thing.

**Comment by kownacki** [comment]
We're gonna have non-deterministic order and so inconcise code, because someone will put capital first and other will put small letter first.

**Comment by merlinnot** [comment]
It is non-deterministic only when two lines are exactly the same besides letter cases.

**Comment by kownacki** [comment]
Ok, but looking at the first letter only, it's nonsense. I would argue not to mix capitalized with non-capitalised.

**Comment by kownacki** [comment]
Ok, let it be case-insensitive.

**Comment by kownacki** [comment]
There is already https://github.com/9e15/guidelines/blob/master/README.md#dependency-ordering so I think we should make a general rule (not just language specific) that dependencies should be sorted as we decided and list all exceptions, like for example `polymer.html` or `_` always on top.

**Comment by merlinnot** [comment]
`_` is not an exception. It's on the top out of the box.

**Comment by kownacki** [comment]
Resolved by https://github.com/9e15/guidelines/pull/20
