### ISSUE TITLE
Module.exports vs exports

### ISSUE THREAD

**Issue by kownacki** [9e15/guidelines#6]
Node js provides shorthand `exports` for `module.exports`. The proposal is to use only `module.exports` and forbid usage of `exports` to make our code more concise and straightforward. Moreover `exports` can be harmful for reasons laid out here: https://github.com/alanjames1987/Node.js-Best-Practices#use-moduleexports-not-exports

In my opinion it's not such a big deal but if you insist I'll agree to quit using `exports` entirely.

**Comment by merlinnot** [comment]
I'd like to choose one of these to keep code consistent. Since sometimes we're forced to use 'module.exports', I'd stick to this one.

**Comment by kownacki** [comment]
Resolved by https://github.com/9e15/guidelines/pull/13
