### ISSUE TITLE
Minimum supported screen resolutions.

### ISSUE THREAD

**Issue by mchyb** [9e15/guidelines#7]
We should specify minimum screen resolution supported in our projects. Common minimum width is 320px. I'm not sure about minimum height. Research needed.

**Comment by merlinnot** [comment]
Minimum height should be 320px, same as width, to support landscape mode on these devices.

**Comment by kownacki** [comment]
I forgot that devices has landscape mode, LOL. Of course it should be minimum 320px for heigth and width then.

**Comment by merlinnot** [comment]
Make a PR and we can merge it.

**Comment by kownacki** [comment]
Resolved by https://github.com/9e15/guidelines/pull/15
