### ISSUE TITLE
Using Object.freeze

### ISSUE THREAD

**Issue by kownacki** [9e15/guidelines#8]
We should use `Object.freeze` when exporting objects with values that should stay unmutaded. I'm thinking about all kinds of `constants.js` files.

I wouldn't be so eager to start using `Object.freeze` inside all other files on a regular basis, because I'm afraid it would be an overkill. But if we really wanted to go big we could think about something more extensive like https://facebook.github.io/immutable-js/

**Comment by merlinnot** [comment]
I'd use it for constants only, at least for now. It makes us a little bit safer and enforces good practice: to use constants as constants ;)

**Comment by kownacki** [comment]
Resolved by https://github.com/9e15/guidelines/pull/14
