### ISSUE TITLE
IIFE in script tags

### ISSUE THREAD

**Issue by kownacki** [9e15/guidelines#9]
I wanted to create some constants and helper functions outside of Polymer elements definitions in driverpal project. To avoid leaking into global scope I have started wrapping code in IIFEs.

Note: It also applies to code written in Polymer 1.

```js
'use strict';

(function() {
  // Useful constants and helper functions here

  // Also 'MyElement' indentifier won't be leaked
  class MyElement extends Polymer.Element {
  ...
})();
```

I think we should make a rule to always use IIFE.

**Comment by merlinnot** [comment]
It's actually not invoked in he example ;) Please fix and make a PR.

**Comment by kownacki** [comment]
Example fixed.

**Comment by mchyb** [comment]
Good idea.

**Comment by kownacki** [comment]
Resolved by https://github.com/9e15/guidelines/pull/16
